
select * from customer limit 20
-- what is the total revenue generated by male vs female customer ?

select gender, Sum(purchase_amount) as revenue 
from customer 
group by gender


--Which customer used a discount but still choses spent more than the average purchase amount ?

SELECT customer,purchase_amount
FROM customer
WHERE discount_applied = 'YES'
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer
);

--Which are the product top 5 highest 




